Вариант 8.
1. Создать квадратную матрицу из случайных целых чисел из
[-4,3] размера 10. Найти и вычислить минор 5 порядка, расположенный на пересечении 1-5 строк и 2-4, 9, 10 столбцов.
Использовать срезы матрицы

In [8]:
import random
import numpy

# Создание матрицы
matrix = [[random.randint(-4, 3) for i in range(10)] for j in range(10)]
# Вывод матрицы на экран
print("Исходная матрица:")
for row in matrix:
    print(row)

# Определение минора
minor = [matrix[i][2:5] + matrix[i][8:10] for i in range(1, 6)]

# Вывод минора на экран
print("Минор 5 порядка, расположенный на пересечении 1-5 строк и 2-4, 9, 10 столбцов:")
for row in minor:
    print(row)
print(numpy.linalg.det(minor))

Исходная матрица:
[-1, 3, -2, -1, 1, 1, 1, 0, -3, -4]
[2, -2, -4, 2, -1, -1, 2, 1, 1, -2]
[3, 1, 1, 0, -4, 3, 2, -2, -2, 2]
[-2, -4, 2, 3, 3, 1, -3, -2, -1, 3]
[2, -1, 1, 3, -2, -4, 0, -2, 2, 3]
[-3, -2, -2, -2, 3, -4, 1, -2, 3, -1]
[-2, 0, -1, -3, 2, 3, -3, 2, 3, -3]
[1, 1, -3, 0, -4, 2, 3, 2, 1, 2]
[0, 3, -3, -1, -2, 2, 3, 1, 2, 2]
[0, -2, 0, -2, 2, 0, 1, -4, -3, 2]
Минор 5 порядка, расположенный на пересечении 1-5 строк и 2-4, 9, 10 столбцов:
[-4, 2, -1, 1, -2]
[1, 0, -4, -2, 2]
[2, 3, 3, -1, 3]
[1, 3, -2, 2, 3]
[-2, -2, 3, 3, -1]
-943.9999999999998


2. Создать две матрицы из случайных вещественных чисел
подходящего размера. Найти их произведение тремя способами:
записав векторный алгоритм умножения матриц; записав матричный алгоритм, записав матрицу С по строкам; проверив с помощью функции np.dot.

In [9]:
import numpy as np

# Создание матриц
m1 = np.random.rand(3, 4)
m2 = np.random.rand(4, 3)

# Векторный алгоритм умножения матриц
result_v = [[sum(m1[i][k]*m2[k][j] for k in range(4)) for j in range(3)] for i in range(3)]

# Матричный алгоритм, запись матрицы С по строкам
result_m = np.zeros((3, 3))
for i in range(3):
    for j in range(3):
        result_m[i][j] = sum(m1[i][k]*m2[k][j] for k in range(4))

# Проверка с помощью функции np.dot
result_np = np.dot(m1, m2)

# Вывод результатов на экран
print("Матрица 1:")
print(m1)
print("Матрица 2:")
print(m2)
print("Результат умножения матриц векторным алгоритмом:")
print(result_v)
print("Результат умножения матриц матричным алгоритмом:")
print(result_m)
print("Результат умножения матриц с помощью функции np.dot:")
print(result_np)


Матрица 1:
[[0.97896202 0.79463576 0.49431054 0.03318193]
 [0.79720778 0.42702679 0.29664684 0.71296003]
 [0.53368209 0.75636731 0.99400216 0.00299571]]
Матрица 2:
[[0.29447989 0.50229942 0.11295102]
 [0.30143339 0.50191187 0.60310691]
 [0.07382467 0.84686943 0.57517683]
 [0.22453954 0.35329082 0.91879168]]
Результат умножения матриц векторным алгоритмом:
[[0.5717573520200138, 1.320908532381929, 0.904628324468729], [0.5454693722288945, 1.1178701957779968, 1.1732743715021858], [0.45920754803218594, 1.4905463422547551, 1.0909297379210987]]
Результат умножения матриц матричным алгоритмом:
[[0.57175735 1.32090853 0.90462832]
 [0.54546937 1.1178702  1.17327437]
 [0.45920755 1.49054634 1.09092974]]
Результат умножения матриц с помощью функции np.dot:
[[0.57175735 1.32090853 0.90462832]
 [0.54546937 1.1178702  1.17327437]
 [0.45920755 1.49054634 1.09092974]]


3. Создать вектор-строку 1x5 из случайных целых чисел. Вычислить норму ‖x‖5
 самостоятельно написанной функцией и
проверить результат с помощью linalg.norm().


In [10]:
# Создание вектор-строки
x = np.random.randint(0, 10, size=5)

def norm(x, p):
    return np.sum(np.abs(x)**p)**(1/p)

# Вычисление нормы ‖x‖5
norm_custom = norm(x, 5)

# Проверка результата с помощью функции linalg.norm()
norm_np = np.linalg.norm(x, ord=5)

# Вывод результатов на экран
print("Вектор-строка x:")
print(x)
print("Норма ‖x‖5, вычисленная самостоятельно:")
print(norm_custom)
print("Норма ‖x‖5, вычисленная с помощью функции linalg.norm():")
print(norm_np)


Вектор-строка x:
[4 0 3 8 1]
Норма ‖x‖5, вычисленная самостоятельно:
8.060977389671754
Норма ‖x‖5, вычисленная с помощью функции linalg.norm():
8.060977389671754


4. Создать матрицу из случайных целых чисел. Найти норму
матрицы ‖A‖1
 с помощью самостоятельно написанного алгоритма, проверить результат с помощью linalg.norm().

In [11]:
# Создание матрицы
A = np.random.randint(-10, 10, size=(5, 5))

# Написание функции вычисления нормы
def norm(A, p):
    if p == 1:
        return np.max(np.sum(np.abs(A), axis=0))
    elif p == np.inf:
        return np.max(np.sum(np.abs(A), axis=1))
    elif p == 2:
        return np.sqrt(np.sum(np.square(A)))
    else:
        raise ValueError("Неподдерживаемое значение p")

# Вычисление нормы ‖A‖1
norm_custom = norm(A, 2)

# Проверка результата с помощью функции linalg.norm()
norm_np = np.linalg.norm(A)

# Вывод результатов на экран
print("Матрица A:")
print(A)
print("Норма ‖A‖1, вычисленная самостоятельно:")
print(norm_custom)
print("Норма ‖A‖1, вычисленная с помощью функции linalg.norm():")
print(norm_np)


Матрица A:
[[-10  -3  -3   3 -10]
 [ -2  -3   1   6  -8]
 [ -8  -3   6  -8  -7]
 [ -9   8  -1  -3  -8]
 [ -5   1  -8  -1   2]]
Норма ‖A‖1, вычисленная самостоятельно:
29.614185789921695
Норма ‖A‖1, вычисленная с помощью функции linalg.norm():
29.614185789921695


5. Для вектора, созданного в третьем пункте, найти отражение Хаусхолдера, которое обнуляет все его координаты, кроме первой.
Например, вектор (1,2,3,4,5) переводит в вектор (a,0,0,0,0).


In [12]:
import numpy as np

def householder_reflection(vector):
    """
    Функция для нахождения отражения Хаусхолдера для одномерного массива
    """
    # Длина вектора
    n = len(vector)

    # Вычисляем норму вектора
    norm = np.linalg.norm(vector)

    # Вычисляем знак первого элемента вектора
    sign = 1 if vector[0] >= 0 else -1

    # Создаем новый вектор, в котором первый элемент равен длине вектора со знаком
    v = np.zeros(n)
    v[0] = -sign * norm

    # Вычитаем из нового вектора исходный вектор
    v = v - vector

    # Вычисляем матрицу отражения Хаусхолдера
    H = np.identity(n) - 2 * np.outer(v, v) / np.dot(v, v)

    # Умножаем матрицу отражения на исходный вектор
    result = H.dot(vector)

    return np.round(result, 8)
print(householder_reflection(x))


[-9.48683298  0.          0.         -0.          0.        ]


6. Для матрицы, созданной в 4 пункте, найти LU разложение
самостоятельно написанной функцией и проверить результат с
помощью перемножения матриц

In [13]:
def lu_decomposition(mtx):
    n = len(mtx)
    lower = np.zeros((n, n))
    upper = np.zeros((n, n))

    for i in range(n):
        lower[i][i] = 1

        for j in range(i, n):
            Sum = 0
            for k in range(i):
                Sum += (lower[i][k] * upper[k][j])
            upper[i][j] = mtx[i][j] - Sum

        for j in range(i+1, n):
            Sum = 0
            for k in range(i):
                Sum += (lower[j][k] * upper[k][i])
            if upper[i][i] == 0:
                return None
            lower[j][i] = (mtx[j][i] - Sum) / upper[i][i]

    return lower, upper

# Пример использования функции
print("Матрица A:")
print(A)
result = lu_decomposition(A)

if result is None:
    print("Матрица не может быть разложена в LU форму")
else:
    L, U = result
    # Проверка, что LU разложение верно
    print("L = ", L)
    print("U = ", U)
    res = np.dot(L, U)
    res = np.round(res).astype(int) # округление элементов матрицы res до int
    if np.allclose(res, A, rtol=1e-5):
        print("LU разложение верно!")
    else:
        print("LU разложение неверно!")
    print("A = ",res)

Матрица A:
[[-10  -3  -3   3 -10]
 [ -2  -3   1   6  -8]
 [ -8  -3   6  -8  -7]
 [ -9   8  -1  -3  -8]
 [ -5   1  -8  -1   2]]
L =  [[ 1.          0.          0.          0.          0.        ]
 [ 0.2         1.          0.          0.          0.        ]
 [ 0.8         0.25        1.          0.          0.        ]
 [ 0.9        -4.45833333  1.10416667  1.          0.        ]
 [ 0.5        -1.04166667 -0.60416667 -0.12676524  1.        ]]
U =  [[-10.          -3.          -3.           3.         -10.        ]
 [  0.          -2.4          1.6          5.4         -6.        ]
 [  0.           0.           8.         -11.75         2.5       ]
 [  0.           0.           0.          31.34895833 -28.51041667]
 [  0.           0.           0.           0.          -1.35371324]]
LU разложение верно!
A =  [[-10  -3  -3   3 -10]
 [ -2  -3   1   6  -8]
 [ -8  -3   6  -8  -7]
 [ -9   8  -1  -3  -8]
 [ -5   1  -8  -1   2]]


7. Для матрицы, созданной в 4 пункте, найти QR разложение
всеми рассмотренными методами, проверить результат с помощью
перемножения матриц и с помощью функции np.linalg.qr.

In [14]:
def householder_reflection(v):
    norm = np.linalg.norm(v)
    if norm == 0:
        v[0] = 1
    else:
        v = v / norm
        if v[0] >= 0:
            v[0] += 1
        else:
            v[0] -= 1
        norm = np.linalg.norm(v)
        v = v / norm
    return v

def qr_householder(A):
    m, n = A.shape
    Q = np.eye(m, dtype=np.float64)
    R = A.copy().astype(np.float64)
    for i in range(n):
        v = R[i:, i].copy()
        v[0] = v[0] + np.sign(v[0]) * np.linalg.norm(v)
        v = householder_reflection(v)
        H = np.eye(m)
        H[i:, i:] -= 2.0 * np.outer(v, v)
        Q = Q.dot(H)
        R = H.dot(R)
    return Q, R
print("Матрица A:\n", A)
Q1, R1 = qr_householder(A)
print("householder")
print("Матрица Q:")
print(Q1)
print("Матрица R:")
print(R1)
print("Q * R:")
print(Q1.dot(R1))
Qb, Rb = np.linalg.qr(A)
def gram_schmidt(A):
    m, n = A.shape
    Q = np.zeros(A.shape, dtype=np.float64)
    R = np.zeros((A.shape[1], A.shape[1]),dtype=np.float64)

    for j in range(n):
        v = A[:, j].astype(np.float64)
        for i in range(j):
            R[i, j] = Q[:, i].T.dot(A[:, j])
            v -= R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]

    return Q, R
Q2, R2 = gram_schmidt(A)
print("gram_schmidt")
print("Матрица Q:")
print(Q2)
print("Матрица R:")
print(R2)
print("Q * R:")
print(Q2.dot(R2))
Qb, Rb = np.linalg.qr(A)
print("np.linalg.qr()")
print("Матрица Q:")
print(Qb)
print("Матрица R:")
print(Rb)
print("Q * R:")
print(Qb.dot(Rb))

Матрица A:
 [[-10  -3  -3   3 -10]
 [ -2  -3   1   6  -8]
 [ -8  -3   6  -8  -7]
 [ -9   8  -1  -3  -8]
 [ -5   1  -8  -1   2]]
householder
Матрица Q:
[[-0.89557861 -0.08923679  0.19789064  0.03880888  0.38640511]
 [-0.06745607 -0.80925758  0.15059588 -0.41797222 -0.37838071]
 [-0.26982426 -0.16999477 -0.86984914  0.28344438 -0.24762555]
 [-0.30355229  0.5492663  -0.07691661 -0.61135807 -0.47590721]
 [-0.16864016  0.08091524  0.41905428  0.60802441 -0.64785264]]
Матрица R:
[[14.82446379  1.10151829  2.6530078   0.14641892 13.47534249]
 [-1.47713172  7.68051309 -2.75810408 -5.4920118   4.32409196]
 [ 3.27567301  1.36780921 -8.93768851  8.26773583  4.35871197]
 [ 0.64240124 -3.99568326 -3.08656981 -3.43291192  7.07849176]
 [ 6.39614275 -3.73630691  2.63537899  2.94550977  3.40792575]]
Q * R:
[[-10.  -3.  -3.   3. -10.]
 [ -2.  -3.   1.   6.  -8.]
 [ -8.  -3.   6.  -8.  -7.]
 [ -9.   8.  -1.  -3.  -8.]
 [ -5.   1.  -8.  -1.   2.]]
gram_schmidt
Матрица Q:
[[-0.60412209 -0.37963923 -0.29789