Вариант 8.
1. Создать квадратную матрицу из случайных целых чисел из
[-4,3] размера 10. Найти и вычислить минор 5 порядка, расположенный на пересечении 1-5 строк и 2-4, 9, 10 столбцов.
Использовать срезы матрицы

In [8]:
import random

# Создание матрицы
matrix = [[random.randint(-4, 3) for i in range(10)] for j in range(10)]
# Вывод матрицы на экран
print("Исходная матрица:")
for row in matrix:
    print(row)

# Определение минора
minor = [matrix[i][2:5] + matrix[i][8:10] for i in range(1, 6)]

# Вывод минора на экран
print("Минор 5 порядка, расположенный на пересечении 1-5 строк и 2-4, 9, 10 столбцов:")
for row in minor:
    print(row)

Исходная матрица:
[-4, -4, -1, 0, 3, 3, 2, 0, 1, -2]
[-3, 1, -1, 1, 1, 1, 0, -4, -2, -2]
[-2, -2, -3, -4, -1, -4, -2, 1, 3, -4]
[0, 2, -2, -4, 1, -4, 3, -2, 3, -1]
[2, -1, -3, -1, -4, -2, -1, 2, 1, 3]
[-4, 0, 0, -1, -1, 3, 0, -2, -4, 2]
[-1, -2, 1, -2, 3, 0, -4, -2, 2, -2]
[-4, -1, 0, -1, 0, 1, 2, 0, 2, -4]
[3, -2, -2, -1, 2, 1, 3, 2, -1, -3]
[-1, -3, 1, -1, -4, 1, 1, -1, 1, -3]
Минор 5 порядка, расположенный на пересечении 1-5 строк и 2-4, 9, 10 столбцов:
[-1, 1, 1, -2, -2]
[-3, -4, -1, 3, -4]
[-2, -4, 1, 3, -1]
[-3, -1, -4, 1, 3]
[0, -1, -1, -4, 2]


2. Создать две матрицы из случайных вещественных чисел
подходящего размера. Найти их произведение тремя способами:
записав векторный алгоритм умножения матриц; записав матричный алгоритм, записав матрицу С по строкам; проверив с помощью функции np.dot.

In [9]:
import numpy as np

# Создание матриц
m1 = np.random.rand(3, 4)
m2 = np.random.rand(4, 3)

# Векторный алгоритм умножения матриц
result_v = [[sum(m1[i][k]*m2[k][j] for k in range(4)) for j in range(3)] for i in range(3)]

# Матричный алгоритм, запись матрицы С по строкам
result_m = np.zeros((3, 3))
for i in range(3):
    for j in range(3):
        result_m[i][j] = sum(m1[i][k]*m2[k][j] for k in range(4))

# Проверка с помощью функции np.dot
result_np = np.dot(m1, m2)

# Вывод результатов на экран
print("Матрица 1:")
print(m1)
print("Матрица 2:")
print(m2)
print("Результат умножения матриц векторным алгоритмом:")
print(result_v)
print("Результат умножения матриц матричным алгоритмом:")
print(result_m)
print("Результат умножения матриц с помощью функции np.dot:")
print(result_np)


Матрица 1:
[[0.16322771 0.1727558  0.21615462 0.02872736]
 [0.68946417 0.51162442 0.37227424 0.3005765 ]
 [0.77206615 0.60176476 0.29369257 0.58218014]]
Матрица 2:
[[0.71696065 0.27765166 0.43210424]
 [0.26950748 0.01972649 0.53576906]
 [0.37439555 0.10386162 0.12851644]
 [0.50491668 0.34376689 0.89473325]]
Результат умножения матриц векторным алгоритмом:
[[0.2590190747709845, 0.0810539928540642, 0.2165713391393141], [0.9233491890837486, 0.34351667699481236, 0.8888120692838439], [1.1196308014758622, 0.4568737941723503, 1.2146602453850497]]
Результат умножения матриц матричным алгоритмом:
[[0.25901907 0.08105399 0.21657134]
 [0.92334919 0.34351668 0.88881207]
 [1.1196308  0.45687379 1.21466025]]
Результат умножения матриц с помощью функции np.dot:
[[0.25901907 0.08105399 0.21657134]
 [0.92334919 0.34351668 0.88881207]
 [1.1196308  0.45687379 1.21466025]]


3. Создать вектор-строку 1x5 из случайных целых чисел. Вычислить норму ‖x‖5
 самостоятельно написанной функцией и
проверить результат с помощью linalg.norm().


In [10]:
# Создание вектор-строки
x = np.random.randint(0, 10, size=5)

def norm(x, p):
    return np.sum(np.abs(x)**p)**(1/p)

# Вычисление нормы ‖x‖5
norm_custom = norm(x, 5)

# Проверка результата с помощью функции linalg.norm()
norm_np = np.linalg.norm(x, ord=5)

# Вывод результатов на экран
print("Вектор-строка x:")
print(x)
print("Норма ‖x‖5, вычисленная самостоятельно:")
print(norm_custom)
print("Норма ‖x‖5, вычисленная с помощью функции linalg.norm():")
print(norm_np)


Вектор-строка x:
[9 6 8 4 0]
Норма ‖x‖5, вычисленная самостоятельно:
10.012309657140182
Норма ‖x‖5, вычисленная с помощью функции linalg.norm():
10.012309657140182


4. Создать матрицу из случайных целых чисел. Найти норму
матрицы ‖A‖1
 с помощью самостоятельно написанного алгоритма, проверить результат с помощью linalg.norm().

In [11]:
# Создание матрицы
A = np.random.randint(-10, 10, size=(5, 5))

# Написание функции вычисления нормы
def norm(A, p):
    if p == 1:
        return np.max(np.sum(np.abs(A), axis=0))
    elif p == np.inf:
        return np.max(np.sum(np.abs(A), axis=1))
    elif p == 2:
        return np.sqrt(np.sum(np.square(A)))
    else:
        raise ValueError("Неподдерживаемое значение p")

# Вычисление нормы ‖A‖1
norm_custom = norm(A, 2)

# Проверка результата с помощью функции linalg.norm()
norm_np = np.linalg.norm(A)

# Вывод результатов на экран
print("Матрица A:")
print(A)
print("Норма ‖A‖1, вычисленная самостоятельно:")
print(norm_custom)
print("Норма ‖A‖1, вычисленная с помощью функции linalg.norm():")
print(norm_np)


Матрица A:
[[ -7  -9  -7   8 -10]
 [ -7   3  -4  -4  -3]
 [ -4  -4  -3   0  -4]
 [  0   0   1  -9   4]
 [  6   5   9  -5  -6]]
Норма ‖A‖1, вычисленная самостоятельно:
28.284271247461902
Норма ‖A‖1, вычисленная с помощью функции linalg.norm():
28.284271247461902


5. Для вектора, созданного в третьем пункте, найти отражение Хаусхолдера, которое обнуляет все его координаты, кроме первой.
Например, вектор (1,2,3,4,5) переводит в вектор (a,0,0,0,0).


In [12]:
import numpy as np

def householder_reflection(vector):
    """
    Функция для нахождения отражения Хаусхолдера для одномерного массива
    """
    # Длина вектора
    n = len(vector)

    # Вычисляем норму вектора
    norm = np.linalg.norm(vector)

    # Вычисляем знак первого элемента вектора
    sign = 1 if vector[0] >= 0 else -1

    # Создаем новый вектор, в котором первый элемент равен длине вектора со знаком
    v = np.zeros(n)
    v[0] = -sign * norm

    # Вычитаем из нового вектора исходный вектор
    v = v - vector

    # Вычисляем матрицу отражения Хаусхолдера
    H = np.identity(n) - 2 * np.outer(v, v) / np.dot(v, v)

    # Умножаем матрицу отражения на исходный вектор
    result = H.dot(vector)

    return np.round(result, 8)
print(householder_reflection(x))


[-14.03566885   0.          -0.          -0.           0.        ]


6. Для матрицы, созданной в 4 пункте, найти LU разложение
самостоятельно написанной функцией и проверить результат с
помощью перемножения матриц

In [13]:
def lu_decomposition(mtx):
    n = len(mtx)
    lower = np.zeros((n, n))
    upper = np.zeros((n, n))

    for i in range(n):
        lower[i][i] = 1

        for j in range(i, n):
            Sum = 0
            for k in range(i):
                Sum += (lower[i][k] * upper[k][j])
            upper[i][j] = mtx[i][j] - Sum

        for j in range(i+1, n):
            Sum = 0
            for k in range(i):
                Sum += (lower[j][k] * upper[k][i])
            if upper[i][i] == 0:
                return None
            lower[j][i] = (mtx[j][i] - Sum) / upper[i][i]

    return lower, upper

# Пример использования функции
print("Матрица A:")
print(A)
result = lu_decomposition(A)

if result is None:
    print("Матрица не может быть разложена в LU форму")
else:
    L, U = result
    # Проверка, что LU разложение верно
    print("L = ", L)
    print("U = ", U)
    res = np.dot(L, U)
    res = np.round(res).astype(int) # округление элементов матрицы res до int
    if np.allclose(res, A, rtol=1e-5):
        print("LU разложение верно!")
    else:
        print("LU разложение неверно!")
    print("A = ",res)

Матрица A:
[[ -7  -9  -7   8 -10]
 [ -7   3  -4  -4  -3]
 [ -4  -4  -3   0  -4]
 [  0   0   1  -9   4]
 [  6   5   9  -5  -6]]
L =  [[ 1.          0.          0.          0.          0.        ]
 [ 1.          1.          0.          0.          0.        ]
 [ 0.57142857  0.0952381   1.          0.          0.        ]
 [-0.          0.          1.4         1.          0.        ]
 [-0.85714286 -0.22619048  5.15       -4.          1.        ]]
U =  [[ -7.          -9.          -7.           8.         -10.        ]
 [  0.          12.           3.         -12.           7.        ]
 [  0.           0.           0.71428571  -3.42857143   1.04761905]
 [  0.           0.           0.          -4.2          2.53333333]
 [  0.           0.           0.           0.          -8.25      ]]
LU разложение верно!
A =  [[ -7  -9  -7   8 -10]
 [ -7   3  -4  -4  -3]
 [ -4  -4  -3   0  -4]
 [  0   0   1  -9   4]
 [  6   5   9  -5  -6]]


7. Для матрицы, созданной в 4 пункте, найти QR разложение
всеми рассмотренными методами, проверить результат с помощью
перемножения матриц и с помощью функции np.linalg.qr.

In [14]:
def householder_reflection(v):
    norm = np.linalg.norm(v)
    if norm == 0:
        v[0] = 1
    else:
        v = v / norm
        if v[0] >= 0:
            v[0] += 1
        else:
            v[0] -= 1
        norm = np.linalg.norm(v)
        v = v / norm
    return v

def qr_householder(A):
    m, n = A.shape
    Q = np.eye(m, dtype=np.float64)
    R = A.copy().astype(np.float64)
    for i in range(n):
        v = R[i:, i].copy()
        v[0] = v[0] + np.sign(v[0]) * np.linalg.norm(v)
        v = householder_reflection(v)
        H = np.eye(m)
        H[i:, i:] -= 2.0 * np.outer(v, v)
        Q = Q.dot(H)
        R = H.dot(R)
    return Q, R
print("Матрица A:\n", A)
Q1, R1 = qr_householder(A)
print("householder")
print("Матрица Q:")
print(Q1)
print("Матрица R:")
print(R1)
print("Q * R:")
print(Q1.dot(R1))
Qb, Rb = np.linalg.qr(A)
def gram_schmidt(A):
    m, n = A.shape
    Q = np.zeros(A.shape, dtype=np.float64)
    R = np.zeros((A.shape[1], A.shape[1]),dtype=np.float64)

    for j in range(n):
        v = A[:, j].astype(np.float64)
        for i in range(j):
            R[i, j] = Q[:, i].T.dot(A[:, j])
            v -= R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]

    return Q, R
Q2, R2 = gram_schmidt(A)
print("gram_schmidt")
print("Матрица Q:")
print(Q2)
print("Матрица R:")
print(R2)
print("Q * R:")
print(Q2.dot(R2))
Qb, Rb = np.linalg.qr(A)
print("np.linalg.qr()")
print("Матрица Q:")
print(Qb)
print("Матрица R:")
print(Rb)
print("Q * R:")
print(Qb.dot(Rb))

Матрица A:
 [[ -7  -9  -7   8 -10]
 [ -7   3  -4  -4  -3]
 [ -4  -4  -3   0  -4]
 [  0   0   1  -9   4]
 [  6   5   9  -5  -6]]
householder
Матрица Q:
[[-0.88643883  0.23383534  0.38267338  0.01806734 -0.113057  ]
 [-0.32238412 -0.93044525 -0.17287719 -0.01424528  0.01583225]
 [-0.1842195   0.18924698 -0.7171734  -0.17745254 -0.62001747]
 [ 0.          0.          0.09632758 -0.98084554  0.1693016 ]
 [ 0.27632925 -0.20923251  0.54777538 -0.07696282 -0.7575505 ]]
Матрица R:
[[10.85661414  9.12932135 10.53423002 -7.18362041  8.9104432 ]
 [ 2.86388638 -6.69900433 -0.36589993  6.63862632  0.95138947]
 [ 4.68677257  1.64487856  5.19062134  0.14707063 -3.34075057]
 [ 0.22127882  0.11965418 -1.21064354  9.41394373 -2.88973265]
 [-1.38465982 -0.24267287 -4.06053045  1.29625308  8.78565256]]
Q * R:
[[-7.00000000e+00 -9.00000000e+00 -7.00000000e+00  8.00000000e+00
  -1.00000000e+01]
 [-7.00000000e+00  3.00000000e+00 -4.00000000e+00 -4.00000000e+00
  -3.00000000e+00]
 [-4.00000000e+00 -4.00000000