Вариант 8.
1. Создать произвольную верхнюю унитреугольную матрицу
А 5 порядка, вектор B произвольный. Решить систему AX = B.

In [1]:
import numpy as np

# Создаем произвольную верхнюю унитреугольную матрицу A
A = np.triu(np.random.rand(5, 5), k=0)
print("Матрица A:")
print(A)

# Создаем произвольный вектор B
B = np.random.rand(5)
print("Вектор B:")
print(B)

# Решаем систему AX=B
if np.linalg.det(A) != 0:
    X = np.linalg.solve(A, B)
    print("Решение системы AX=B:")
    print(X)
else:
    print("Матрица A вырождена и не имеет обратной.")

Матрица A:
[[0.24479793 0.12028857 0.49937626 0.34434074 0.27869072]
 [0.         0.56073389 0.35566698 0.73769027 0.72922228]
 [0.         0.         0.51507074 0.53304832 0.17330432]
 [0.         0.         0.         0.37935296 0.01353088]
 [0.         0.         0.         0.         0.93823958]]
Вектор B:
[0.78399339 0.50575052 0.56683088 0.66679271 0.59864042]
Решение системы AX=B:
[ 2.69408906 -1.63327957 -0.90969811  1.73495257  0.63804643]


2. Решить систему, используя LU разложение
{
1.7 x1+10 x2−1.3 x3+2.1 x4=3.3
3.1 x1+1.7 x2−2.1 x3+5.4 x4=2.1
3.3 x1−7.7 x2+4.4 x3−5.1 x4=1.9
10 x1−20.1 x2+24 x3+1.7 x4=1.8
}

In [2]:
import scipy.linalg
# Задаем матрицу A и вектор B
A = np.array([[1.7, 10, -1.3, 2.1],
              [3.1, 1.7, -2.1, 5.4],
              [3.3, -7.7, 4.4, -5.1],
              [10, -20.1, 24, 1.7]])
B = np.array([3.3, 2.1, 1.9, 1.8])

# LU разложение
P, L, U = scipy.linalg.lu(A)

# Решаем систему уравнений
y = np.linalg.solve(L, P.dot(B))
x = np.linalg.solve(U, y)

# Выводим решение
print("Решение системы уравнений:")
print(x)


Решение системы уравнений:
[ 0.95768639  0.06571745 -0.23327448 -0.32785627]


3. Решить систему из пункта 2 с помощью QR разложения матрицы А. QR разложение найти методом Грама-Шмидта.
Проверить полученное решение непосредственной подстановкой в исходную систему, а также методом np.solve.

In [3]:
# QR разложение матрицы A методом Грама-Шмидта
def gram_schmidt(A):
    m, n = A.shape
    Q = np.zeros(A.shape, dtype=np.float64)
    R = np.zeros((A.shape[1], A.shape[1]),dtype=np.float64)

    for j in range(n):
        v = A[:, j].astype(np.float64)
        for i in range(j):
            R[i, j] = Q[:, i].T.dot(A[:, j])
            v -= R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]

    return Q, R
# Решаем систему уравнений
Q, R = gram_schmidt(A)
y = np.dot(Q.T, B)
x = np.linalg.solve(R, y)

# Выводим решение
print("Решение системы уравнений:")
print(x)

# Проверяем решение
print("Проверка решения:")
print(np.allclose(np.dot(A, x), B))

# Проверяем решение методом np.solve
x_np = np.linalg.solve(A, B)
print("Проверка решения методом np.solve:")
print(np.allclose(x, x_np))

Решение системы уравнений:
[ 0.86978437  0.21509547 -0.09211162 -0.2139682 ]
Проверка решения:
True
Проверка решения методом np.solve:
True


4. Решить систему методом простых итераций с точностью до 10−3. Проверить выполнение достаточного условия сходимости.
Если условие не выполняется, в программе выполнить эквивалентные преобразования системы, после этого привести к удобному
для итераций виду. Оформить итерации в виде таблицы (можно пользоваться модулями PrettyTable или Pandas).
{
3.6 x1+1.8 x2−4.7 x3=3.8
2.7 x1−3.6 x2+1.9 x3=0.4
1.5 x1+4.5 x2+3.3 x3=−1.6
}

In [4]:
from prettytable import PrettyTable

# исходная система
A = np.array([[3.6, 1.8, -4.7],
              [2.7, -3.6, 1.9],
              [1.5, 4.5, 3.3]])
b = np.array([3.8, 0.4, -1.6])

# приведение системы к виду x = Bx + c
B = np.zeros((3, 3))
c = np.zeros(3)
for i in range(3):
    c[i] = b[i] / A[i, i]
    for j in range(3):
        if i != j:
            B[i, j] = -A[i, j] / A[i, i]

# проверка достаточного условия сходимости
if np.max(np.abs(np.linalg.eigvals(B))) >= 1:
    print('Достаточное условие сходимости не выполняется')
    # выполнение эквивалентных преобразований системы
    A[0, :] /= 3.6
    A[0, 0] = 1
    A[1, :] /= 2.7
    A[1, 1] = 1
    A[2, :] /= 3.3
    A[2, 2] = 1
    b /= np.diag(A)
    B = np.zeros((3, 3))
    c = np.zeros(3)
    for i in range(3):
        c[i] = b[i] / A[i, i]
        for j in range(3):
            if i != j:
                B[i, j] = -A[i, j]

# начальное приближение и точность
x0 = np.zeros(3)
eps = 0.01

# итерации
x = x0
table = PrettyTable(['k', 'x1(k)', 'x2(k)', 'x3(k)'])
while True:
    x_new = np.zeros(3)
    x_new[0] = 1.3056*x[2] - 0.5*x[1] + 1.0556
    x_new[1] = 0.1481*x[2] + 0.1111*x[0] + 0.1481
    x_new[2] = -0.4848*x_new[0] - 1.3636*x_new[1] - 0.4848
    table.add_row([len(table._rows), round(x_new[0], 4), round(x_new[1], 4), round(x_new[2], 4)])
    if np.max(np.abs(x_new - x)) < eps:
        break
    x = x_new

print(table)
print('Решение системы: x1 ≈ {}, x2 ≈ {}, x3 ≈ {}'.format(round(x[0], 3), round(x[1], 3), round(x[2], 3)))


Достаточное условие сходимости не выполняется
+---+---------+--------+---------+
| k |  x1(k)  | x2(k)  |  x3(k)  |
+---+---------+--------+---------+
| 0 |  1.0556 | 0.1481 | -1.1985 |
| 1 | -0.5832 | 0.0879 | -0.3219 |
| 2 |  0.5914 | 0.0356 | -0.8201 |
| 3 | -0.0329 | 0.0923 | -0.5948 |
| 4 |  0.2329 | 0.0564 | -0.6746 |
| 5 |  0.1467 | 0.0741 | -0.6569 |
| 6 |  0.1609 | 0.0671 | -0.6543 |
| 7 |  0.1678 | 0.0691 | -0.6603 |
+---+---------+--------+---------+
Решение системы: x1 ≈ 0.161, x2 ≈ 0.067, x3 ≈ -0.654


5. Найти псевдорешение системы:
{
3.6 x1+1.8 x2−4.7 x3=3.8
2.7 x1−3.6 x2+1.9 x3=0.4
1.5 x1+4.5 x2+3.3 x3=−1.6
5.6 x1+8.8 x2−6.7 x3=7.3
}

In [5]:
import numpy as np

# коэффициенты системы
A = np.array([[3.6, 1.8, -4.7], [2.7, -3.6, 1.9], [1.5, 4.5, 3.3], [5.6, 8.8, -6.7]])

# свободные члены
b = np.array([3.8, 0.4, -1.6, 7.3])

# решение методом наименьших квадратов
x = np.linalg.lstsq(A, b, rcond=None)[0]

# вывод результатов
print("Псевдорешение системы:")
print("x1 =", x[0])
print("x2 =", x[1])
print("x3 =", x[2])


Псевдорешение системы:
x1 = 0.4791656592169841
x2 = 0.009396086421513405
x3 = -0.6072163704324065
